Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,18 +25,18 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Determine branch name
-          id: set-branch
-            run: |
-              if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-                if [ -z "${{ github.event.inputs.environment }}" ]; then
-                  echo "Error: 'environment' input is required for manual runs."
-                  exit 1
-                fi
-                BRANCH_NAME="${{ github.event.inputs.environment }}"
-              else
-                BRANCH_NAME="${{ github.ref_name }}"
-              fi
-              echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+        id: set-branch
+        run: |
+          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
+            if [ -z "${{ github.event.inputs.environment }}" ]; then
+              echo "Error: 'environment' input is required for manual runs."
+              exit 1
+            fi
+            BRANCH_NAME="${{ github.event.inputs.environment }}"
+          else
+            BRANCH_NAME="${{ github.ref_name }}"
+          fi
+          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
 
       - name: Install snowflake-cli
         uses: Snowflake-Labs/snowflake-cli-action@v1.5
